feat(git): add hook to automatically run tests before committing

diff --git a/.dev/githooks/pre-commit b/.dev/githooks/pre-commit
--- a/.dev/githooks/pre-commit
+++ b/.dev/githooks/pre-commit
@@ -1,1 +1,11 @@
 #!/bin/bash
+#
+# Run tests before committing, and abort if the tests fail
+
+cmake --build build --target Test
+../.././build/Test
+result=$?
+if test $result -ne 0
+then echo "Your tests are failing - Aborting commit"
+fi
+exit $result
